### ISSUE TITLE
FAQ | Move markdown to new portal bridge repo

### ISSUE THREAD

**Issue by mliu-xlabs** [XLabs/portal-bridge-ui#185]
**Technical Story**
Since the legacy FAQ is being deprecated, we need to find a new place to host the markdown

**Tasks**
- Assume same look and feel for design
- [x] Migrate all existing content - 
https://docs.wormhole.com/wormhole/faqs
- [x] Create new content pages using: `https://github.com/wormhole-foundation/docs.wormhole.com/blob/main/tutorial-recovery-workflow.md`. Content described in: https://github.com/XLabs/portal-bridge-ui/issues/191

**Content Areas**
- Liquid Markets (https://docs.wormhole.com/wormhole/overview-liquid-markets)
- Tutorial recovery workflow (https://docs.wormhole.com/wormhole/tutorial-recovery-workflow)
- video tutorial how to manually add tokens to your wallet (https://docs.wormhole.com/wormhole/video-tutorial-how-to-manually-add-tokens-to-your-wallet)
- Token Migration Tutorial (This we need to find. I can't find it)

**Content Edits**

![Image](https://github.com/XLabs/portal-bridge-ui/assets/130170527/5ff35700-a0e1-444f-82c4-f7721b361844)
- Remove "If you still have V1 wrapped assets that are not eligible for migration, please lodge a Github issue or reach out to our community managers on discord."

**Additional Information**
- @barnji moved legacy repo to this location: https://github.com/wormhole-foundation/docs.wormhole.com/tree/archive

```[tasklist]
### Tasks
- [ ] https://github.com/XLabs/portal-bridge-ui/issues/190
- [ ] https://github.com/XLabs/portal-bridge-ui/issues/191
- [ ] https://github.com/XLabs/portal-bridge-ui/issues/189
```

**Comment by mliu-xlabs** [comment]
https://github.com/wormhole-foundation/docs.wormhole.com/tree/archive 

can also check here for old docs
