### ISSUE TITLE
[feat] - Add sei native transfer support

### ISSUE THREAD

**Issue by sebastianscatularo** [XLabs/portal-bridge-ui#199]
## Scenario:

As a user, I want to do native transfers for Sei

## Acceptance Criteria

**Given** a user with Sei coin at Sei chain
**When** he/her bridge to another chain
**Then** he/her receives a wrapped asset as a result

**Given** a user with Sei coin at another chain than Sei
**When** he/her bridge back to Sei
**Then** he/her receives an unwrapped Sei coin

## Technical Information

Example implementation:

- https://github.com/wormhole-foundation/example-token-bridge-ui/pull/64
- https://github.com/XLabs/portal-bridge-ui/pull/157
```[tasklist]
### Tasks
- [ ] https://github.com/XLabs/portal-bridge-ui/issues/297
- [ ] https://github.com/XLabs/portal-bridge-ui/issues/426
- [ ] https://github.com/XLabs/portal-bridge-ui/issues/427
- [ ] https://github.com/XLabs/portal-bridge-ui/issues/430
- [ ] https://github.com/XLabs/portal-bridge-ui/issues/428
- [ ] https://github.com/XLabs/portal-bridge-ui/issues/443
```

**Comment by sebastianscatularo** [comment]
on hold waiting Sei to be active at mainnet

**Comment by mliu-xlabs** [comment]
From Tony:
It'd be good to include Sei in Portal in your next sprint planning cycle, but it's not worth killing yourself over. If you're mid-progress on tBTC that is more important IMO.

Example if we need but likely not:
https://github.com/wormhole-foundation/example-token-bridge-ui/pulls?q=is%3Apr+sei


Summary: We are prioritizing launch of tbtc solana ahead of getting sei ready.

**Comment by hernandiegosavio** [comment]
Check issue https://github.com/XLabs/portal-bridge-ui/issues/297 to see if we can close once it's deployed

**Comment by sebastianscatularo** [comment]
@SamantaCasal could you test it?
- https://testnet.portal-bridge-ui.pages.dev/16dea3b237/#/transfer
- https://preview.portal-bridge-ui.pages.dev/16dea3b237/#/transfer

**Comment by SamantaCasal** [comment]
Sending Sei(kprl)  from Sei to Avalanche (Metamask): 
FYI: @sebastianscatularo 
❗ The following error is displayed in 3rd step: 
`useHandleTransfer.tsx:183 
Error: Error when broadcasting tx E5A7BE9D3157DA1D8B0E074BB8AF203B38B72B9EF71FD961A23F71DD13126DC9 at height 30913690. Code: 29; Raw log: failed to execute message; message index: 1: dispatch: submessages: dispatch: submessages: cannot send packet using client (07-tendermint-55) with status Expired: client is not active`

https://github.com/XLabs/portal-bridge-ui/assets/69044575/08c1e5f5-754d-4971-b31d-7821f28f1d75

**Comment by SamantaCasal** [comment]
QA OK! 
FYI: @sebastianscatularo 
Txs:
[SNOWTRACE](https://snowtrace.io/tx/0x964494d3389d080ad972becfcbd1a332df11f5446df3bcb8d4c89cafc3f03229)
[SEISCAN](https://www.seiscan.app/pacific-1/txs/8A84577EA8473A9B22F0265568FFC4DA148DDB90C7875645856D97A05E4E99F7)

![Image](https://github.com/XLabs/portal-bridge-ui/assets/69044575/c0717d79-fbc4-425a-b3c5-53f41d2def8e)

**Comment by sebastianscatularo** [comment]
I'm closing it as complete since the only one pending bug is low
