### ISSUE TITLE
[connect > portal] - Required Features

### ISSUE THREAD

**Issue by sebastianscatularo** [XLabs/portal-bridge-ui#483]
```[tasklist]
### Tasks
- [ ] https://github.com/XLabs/portal-bridge-ui/issues/539
- [ ] https://github.com/XLabs/portal-bridge-ui/issues/535
- [ ] https://github.com/XLabs/portal-bridge-ui/issues/552
- [ ] https://github.com/XLabs/portal-bridge-ui/issues/550
- [ ] https://github.com/XLabs/portal-bridge-ui/issues/534
- [ ] https://github.com/XLabs/portal-bridge-ui/issues/554
- [ ] https://github.com/XLabs/portal-bridge-ui/issues/531
- [ ] https://github.com/XLabs/portal-bridge-ui/issues/556
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/1181
- [ ] https://github.com/XLabs/portal-bridge-ui/issues/484
- [ ] https://github.com/XLabs/portal-bridge-ui/issues/485
- [ ] https://github.com/XLabs/portal-bridge-ui/issues/486
- [ ] https://github.com/XLabs/portal-bridge-ui/issues/487
- [ ] https://github.com/XLabs/portal-bridge-ui/issues/488
- [ ] https://github.com/XLabs/portal-bridge-ui/issues/480
- [ ] https://github.com/XLabs/portal-bridge-ui/issues/479
- [ ] https://github.com/XLabs/portal-bridge-ui/issues/523
- [ ] https://github.com/XLabs/portal-bridge-ui/issues/520
- [ ] https://github.com/XLabs/portal-bridge-ui/pull/540
- [ ] https://github.com/XLabs/portal-bridge-ui/issues/530
- [ ] https://github.com/XLabs/portal-bridge-ui/issues/541
- [ ] https://github.com/XLabs/portal-bridge-ui/issues/543
- [ ] https://github.com/XLabs/portal-bridge-ui/issues/544
- [ ] https://github.com/XLabs/portal-bridge-ui/issues/546
- [ ] https://github.com/XLabs/portal-bridge-ui/issues/547
- [ ] https://github.com/XLabs/portal-bridge-ui/issues/553
```

**Comment by sebastianscatularo** [comment]
Closing it since we did the cut over
